yakachoisir/intraAsso/urls.py
from django.urls import path
from django.conf.urls import url
from . import views
from . import feed

app_name = 'intraAsso'
urlpatterns = [
    path('home/', views.accueil, name='accueil'),
    path('connexion/', views.connexion, name='connexion'),
    path('inscription/', views.signup, name='inscription'),
    path('associations/', views.associationView, name='associations'),
    path("associations/<int:name>/", views.detail, name="detail"),
    path("postule/<int:name>/", views.create_post, name="create_post"),
    path('logout/', views.logoutView, name='logout'),
    path('', views.redir, name='redir'),
    path('logged/', views.logged, name='logged'),
    path('enacs/', views.enacs, name='enacs'),
    path('enacs/<int:name>/', views.edit_enacs, name='edit_enacs'),

    path('change_bureau/<int:name>/', views.change_bureau, name='change_bureau'),
    path('edit_asso/<int:name>/', views.edit_asso, name='edit_asso'),

    path('Rss/', feed.Actualites(), name='actualite'),
    path('Actualités/<int:name>/', views.actu, name='actu'),
    path('Création_actualité/<int:name>/', views.create_actu, name='create_actu'),
    path('Création_commentaire/<int:name>/', views.create_comment, name='create_comment'),
    path('Edition_commentaire/<int:name>/', views.edit_comment, name='edit_comment'),
    path('liked/<int:name>/', views.like, name='like'),
    path('abonne/<int:name>/', views.abonne, name='abonne'),

    path("postule/refuse/<int:name>/", views.refu_post, name="refu_post"),
    path("postule/accept/<int:name>/", views.validation_post, name="validation_post"),

    path("associations/quit/<int:name>/", views.kick, name="kick"),

    path('search/', views.research, name="research"),
    path('user/<int:name>', views.show_user, name="show_user"),

    path('creation_association/', views.create_asso, name="create_asso"),
    path('creation_association/<str:name>', views.demand_asso, name="demand_asso"),
    path('creation_association/<str:name>', views.demand_asso, name="validate_asso"),
    path('creation_association/accept/<int:name>', views.validation_asso, name="yes_asso"),
    path('creation_association/refuse/<int:name>', views.refu_asso, name="no_asso"),

    path('import/association/', views.export_asso, name="export_asso"),
    path('import/member/', views.export_bureau, name="export_bureau"),
    path('import/enacs/', views.export_enacs, name="export_enacs"),

    path('reset_mdp/', views.edit_password, name="edit_password"),
    path('user/<int:name>', views.edit_password, name="change_pass"),
]

yakachoisir/yakachoisir/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('IntraAsso/', include('intraAsso.urls')),
    path('', views.redir, name='redir'),
    path('accounts/profile/', views.accueil, name='accueil'),
    path('admin/', admin.site.urls),
    url(r'^auth/', include('social_django.urls', namespace='social')),
    url(r'^auth/complete/epita/logged', views.redir2, name="redir2"),
]

yakachoisir/intraAsso/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from .models import User, Member, Association, Creation_association

class UserIsPresent(forms.Form):
    email = forms.EmailField(label="email", max_length=64, required=True, widget=forms.TextInput(attrs={'placeholder':'email'}))
    password = forms.CharField(label="password", required=True, widget=forms.PasswordInput(attrs={'placeholder':'password'}))

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=64, required=True)
    last_name = forms.CharField(max_length=64, required=True)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2', )

class Creation_Assos(ModelForm):
    class Meta:
        model = Creation_association
        fields = ('name', 'mail', 'site', 'description', 'President', 'Vice_president', 'Secretaire' , 'Trésorier', 'Association_tutrice', 'motivation', 'contract', )

class Postulat(forms.Form):
    motivation = forms.FileField(label="Motivation",  required=False,  widget=forms.FileInput(attrs={'accept':'application/pdf'}))

class Edit_Asso(forms.Form):
    name = forms.CharField(label="Nom", max_length=64, required=False)
    mail = forms.EmailField(label="Mail", max_length=64,  required=False)
    site = forms.CharField(label="Site internet", max_length=64, required=False)
    description = forms.CharField(label="Description",  required=False, widget=forms.Textarea)
    motivation = forms.BooleanField(label="Motivation",  required=False)
    contrat = forms.FileField(label="Contrat",  required=False, widget=forms.FileInput(attrs={'accept':'application/pdf'}))


class Change_Password(UserCreationForm):
    class Meta:
        model = User
        fields = ('password1', 'password2', )

class Create_actu(forms.Form):
    titre = forms.CharField(label="titre", max_length=128, required=True)
    description = forms.CharField(label="Description",  required=True, widget=forms.Textarea)

class Create_comment(forms.Form):
    comment = forms.CharField(label="Commentaire",  required=True, widget=forms.Textarea)

yakachoisir/intraAsso/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.utils import timezone
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from django.contrib.syndication.views import Feed
from django.contrib.postgres.search import SearchVector
from django.core.mail import send_mail
from django.core.mail import EmailMessage
from django.conf import settings
from django.forms.models import modelformset_factory
from django.db.models import Q

from .resources import AssoRessource, MemberRessource
from .forms import UserIsPresent, SignUpForm, Creation_Assos, Postulat, Edit_Asso, Change_Password, Create_actu, Create_comment
from .models import User, Association, Rss_files, Status, Creation_association, Member, Tuteur, Role, Postulant, Enacs, Transaction, Budget_request, Reaction, Liked, Rss_subscription

################################################################################

def change_bureau(request, name):
    association = Association.objects.get(id=name)
    members = association.get_members()
    president = association.get_president()
    if request.method == 'GET':
        if (request.user.is_staff):
            if (request.GET.get('Pr') and request.GET.get('Vp') and request.GET.get('Se') and request.GET.get('Tr')):
                return edit_res_bureau(request, name)
        else:
            if (request.GET.get('Vp') and request.GET.get('Se') and request.GET.get('Tr')):
                return edit_bureau(request, name)
    role = Role.objects.get(role_str="None")
    nobody = Member.objects.filter(association=association, role=role)
    post = Postulant.objects.filter(association=association)
    al = Member.objects.filter(association=association)
    context = { "association" : association, "president" : president, "edit" : 1,
                    "members" : members, "nobody" : nobody, "postulants" : post, "all" : al}
    if association.club:
        tut = Tuteur.objects.get(son=association.id).mother
        context["tuteur"]=tut
    return render(request, "intraAsso/assos_president.html", context)

################################################################################

def signup(request):
    if request.user.is_authenticated:
        return redirect(reverse('intraAsso:accueil'))
    if request.method == 'POST':
        form = SignUpForm(request.POST or None)
        if form.is_valid():
            username = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            form.save()
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            email(
                "Incription intranet Epita",
                "Votre inscription à l'intranet des associations d'EPITA est terminé.",
                [username, ]
            )
            return redirect(reverse('intraAsso:accueil'))
    else:
        form = SignUpForm(request.POST or None)
    return render(request, "intraAsso/inscription.html", {"form" : form})

################################################################################

def connexion(request):
    if request.user.is_authenticated:
        return redirect(reverse('intraAsso:accueil'))
    if request.method == 'POST':
        form = UserIsPresent(request.POST or None)
        if form.is_valid():
            mail = form.cleaned_data.get("email")
            mdp = form.cleaned_data.get("password")
            user = authenticate(username=mail, password=mdp)
            if user is None:
                return render(request, "intraAsso/connexion.html", {"form" : form})
            login(request, user)
            return redirect(reverse('intraAsso:accueil'))
    else:
        form = UserIsPresent(request.POST or None)
    return render(request, "intraAsso/connexion.html", {"form" : form})

################################################################################

def create_asso(request):
    if not request.user.is_authenticated:
        return redirect(reverse('intraAsso:connexion'))
    if request.method == 'POST':
        form = Creation_Assos(request.POST, request.FILES)
        if form.is_valid():
            Contract = form.cleaned_data.get('contract')
            creat = form.save(commit=False)
            list = []
            list.append(creat.President.id)
            list.append(creat.Vice_president.id)
            list.append(creat.Secretaire.id)
            list.append(creat.Trésorier.id)
            if (not check_double(list)):
                return render(request, "intraAsso/creat_asso.html", {"form" : form})
            name = creat.name
            try:
                asso = get_object_or_404(Association, name=name)
                return render(request, "intraAsso/creat_asso.html", {"form" : form})
            except:
                pass
            creat.user = request.user
            status = Status.objects.get(status="Reçu")
            creat.status = status
            creat.contract = Contract
            creat.save()
            email(
                "Creation association",
                "Votre demande de création de l'association " + name + " a été reçue.",
                [request.user.email, ]
            )
            return redirect(reverse('intraAsso:accueil'))
    else:
        form = Creation_Assos(request.POST, request.FILES)
    return render(request, "intraAsso/creat_asso.html", {"form" : form})

################################################################################

class AssociationView(generic.ListView):
    template_name = 'intraAsso/assos_list.html'
    context_object_name = 'liste'
    queryset = Association.objects.all().order_by("name")

################################################################################

# quick and dirty

def associationView(request):
    if request.user.is_authenticated:
        return AssociationView.as_view()(request)
    return redirect(reverse('intraAsso:connexion'))

################################################################################

def redir(request):
    if request.user.is_authenticated:
        return redirect(reverse('intraAsso:accueil'))
    return redirect(reverse('intraAsso:connexion'))

################################################################################

def logoutView(request):
    if request.user.is_authenticated:
        logout(request)
        return render(request, "intraAsso/logout.html")
    return redirect(reverse('intraAsso:connexion'))

################################################################################ ################check this fct !!!!

def detail(request, name):
    ##### Pärtie 1 #####
    association = Association.objects.get(id=name)
    form = Postulat(request.POST, request.FILES)
    members = association.get_members()
    president = association.get_president()
    enacs = Enacs.objects.all()[0]
    abonne = 0
    try:
        user = request.user
        p =  Rss_subscription.objects.get(user=user, association=association)
        abonne = 1
    except:
        abonne = 0
    ##### Pärtie 2 #####
    if request.method == 'POST':
        if form.is_valid():
            if association.motivation:
                Motivation = form.cleaned_data.get("motivation")
                if Motivation is not None:
                    try:
                        pos = Postulant.objects.get(user=request.user, association=association)
                    except:
                        p = Postulant(user=request.user,
                                      association=association,
                                      motiv_file=Motivation,
                                      status=Status.objects.get(status="Reçu"))
                        p.save()
                        email = EmailMessage(
                            "Demande d'admission",
                            "L'utilisateur " + p.user.__str__() + " souhaite intéger votre association " + p.association.name + ".",
                            'intranetepita@gmail.com',
                            [president.user.email,],
                        )
                        email.attach_file(p.motiv_file.name)
                        email.send()
    ##### Pärtie 3 #####
    context = { "association" : association, "president" : president,
                "members" : members, "form" : form, "enacs" : enacs}
    context["abonne"]=abonne
    if association.club:
        tut = Tuteur.objects.get(son=association.id).mother
        context["tuteur"]=tut
    try:
        user = get_object_or_404(Member, user=request.user, association=association)
    except:
        if (not request.user.is_staff):
            ke = 1
            try:
                Postulant.objects.get(user=request.user, association=association)
            except:
                ke = 0
            context["k"]=ke
            return render(request, "intraAsso/profil_assos.html", context)
    ##### Pärtie 4 #####
    role = Role.objects.get(role_str="None")
    nobody = Member.objects.filter(association=association, role=role)
    post = Postulant.objects.filter(association=association)
    context = { "association" : association, "president" : president, "edit" : 0,
                    "members" : members, "nobody" : nobody, "postulants" : post, "enacs" : enacs}
    context["abonne"]=abonne
    if association.club:
        tut = Tuteur.objects.get(son=association.id).mother
        context["tuteur"]=tut
    if (request.user.is_staff or user.role.role_str == "President"):
        return render(request, "intraAsso/assos_president.html", context)
    if (user.role.role_str == "Vice-President"):
        return render(request, "intraAsso/assos_vice_president.html", context)
    if (user.role.role_str == "Tresorier"):

yakachoisir/intraAsso/templates/intraAsso/assos_president.html
<html>
  <head>
    <meta charset="utf-8" content="width=device-width, initial-scale=1">
    <time></time>
    <title></title>
    {% load static %}
    <link rel="stylesheet" type = "text/css" href="{% static 'intraAsso/bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'intraAsso/yaka.css'%}" media="all"/>
    <style type= "text/css">
      .asteriskField{display: none;}
    </style>
  </head>
  <body class="text-center" style="background-image :url({% static 'intraAsso/image/backgroundEPITA.png'%})">
    <div class="topnav container-fluid" style="z-index: 1">
      <a href="https://www.epita.fr/">
        <img src="{% static 'intraAsso/image/Epita.png'%}" alt="" width="100px" height="64px" align="left" style=" margin-top:-25px">
      </a>
      <a class="active" align= "left"  href="{% url 'intraAsso:accueil' %}">Accueil</a>
      <a class="lien" href="{% url 'intraAsso:show_user' request.user.id %}">Mon Profil</a>
      <a class="lien"  align ="left"  href="{% url 'intraAsso:associations' %}">Association</a>
      {% if not request.user.is_staff %}
      <a class="lien"  align="left"  href="{% url 'intraAsso:create_asso' %}">Création d'association</a>
      {% endif %}
      <a class="lien"  align="left"  href="{% url 'intraAsso:actualite' %}">Actualités</a>
      <a class="lien" align= "right" style = "float : right"href="{% url 'intraAsso:logout' %}">Déconnexion</a>
      <h5 class= "bar" style="color: white;" align= "right">{{ request.user.first_name }} {{ request.user.last_name }}</h5>

      <form id="searchform" action="{% url 'intraAsso:research' %}" method="get" accept-charset="utf-8">
        <input class="searchfield" id="searchbox" name="q" type="text" placeholder="Recherche">
      </form>
    </div>
    <br><br>
    {% if association.club %}
    <h1 style="color: white"> Club "{{ association.name }}"<br><br>
      Association Tutrice "{{tuteur.name}}"
    </h1>

    {% else %}
    <h1 style="color: white">Association "{{ association.name }}"</h1>

    {% endif %}


    <br>
    <div class="row">


      <div class="col-md-4"></div>
      <div style="color: white"  class="col-md-4" >
        <div align="left">  <font style="font-weight:bold; text-align: justify-all;"> Description :</font>  {{association.description}}</div>
        <br>
        <div align="left">  <font style="font-weight:bold"> Site Web Officiel :</font>
          {% if association.site != "" %}
          <a class = "link" style= "color: white" href="{{association.site}}">{{association.site}}</a>
          {% else %}
          Aucun
          {% endif %}
        </div>
        <div align ="left">  <font style="font-weight:bold"> Adresse Mail Officiel :</font> {{association.mail}}</div>
        <br>
         {% if abonne == 0%}
        <a  href="{% url 'intraAsso:abonne' association.id %}"><button align=type="submit" class="btn btn-success btn-sm">S'abonner </button></a>
        {% else %}
        <a  href="{% url 'intraAsso:abonne' association.id %}"><button align=type="submit" class="btn btn-danger btn-sm">Se désabonner </button></a>
        {% endif %}
        <br><br>
        <a  href="{% url 'intraAsso:edit_asso' association.id %}"> <button align=type="submit" class="btn btn-danger btn-sm">Editer les informations </button></a>
        {% if  enacs.enabled %}
        <a  href="{% url 'intraAsso:edit_enacs' association.id %}"><button align=type="submit" class="btn btn-danger btn-sm">Editer les points Enacs </button></a>
        {% endif%}
        {% if not request.user.is_staff %}
        <a  href="{% url 'intraAsso:create_actu' association.id %}"><button align=type="submit" class="btn btn-danger btn-sm">Créer une actualité</button></a>
        {% endif%}
        <br><br><br>
        </div>
      <div style="color: white" class="col-md-1"></div>
    </div>

    <div class="row">
      <div class="col-md-2"></div>
      <div style="color: white"  class="col-md-3" >
        <h4>Postulant :</h4><br>
        {% for l in postulants %}
        {{ l.user }}
        <a href="{% url 'intraAsso:validation_post' l.id %}"><button type="submit" class="btn btn-sm btn-success">
            Accepter</button></a>
        <a href="{% url 'intraAsso:refu_post' l.id %}"><button type="submit" class="btn btn-sm btn-danger">Refuser</button></a>
        <br><br>
        {% endfor %}
      </div>
      <div style="color: white"  class="col-md-3" >
        <div>
          <h4 style="text-align: left"> Membres :</h4><br>

          {% for l in nobody %}
          <div align="left"><a  href="{% url 'intraAsso:show_user' l.user.id %}"  style="color:white; text-decoration:none">{{ l.user }}</a>
            <a  href="{% url 'intraAsso:kick' l.id %}"> <button type="button" class="btn btn-danger btn-sm" size="0">Expulser</button></a></div>

          <br>
          {% endfor %}
        </div>

      </div>

      <div align ="left" style="text-align: left;color: white" class="col-md-3">
        <h4> Bureau :</h4><br>
        <div align="left"><a href="{% url 'intraAsso:show_user' president.user.id %}" style="color:white; text-decoration:none"> <font style="font-weight:bold">{{ president.role.role_str }}: </font>{{ president.user }} </a></div>
        {% for l in members %}
        <div align="left"><a href="{% url 'intraAsso:show_user' l.user.id %}"  style="color:white; text-decoration:none" > <font style="font-weight:bold">{{ l.role.role_str }}: </font>{{ l.user }} </a></div>
        {% endfor %}
        <br>

        {% if edit == 0 %}
        <a  href="{% url 'intraAsso:change_bureau' association.id %}"><button align=type="submit" class="btn btn-danger btn-sm">
            Changer le bureau</button></a>
        {% endif%}
        <br><br>

        {% if edit == 1 %}

        {% if request.user.is_staff %}
        <div class="dropdown">
          <FORM method="get" id="form1" style="color:white">

            President : &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            <SELECT   class="" name="Pr" size="1"  size="1"  style="width: 180px;">
              {% for l in all %}
              {% if l.role.role_str == 'President' %}
              <OPTION selected> {{l.user}}
                {% else%}
              <OPTION>{{l.user}}
                {% endif%}
                {% endfor %}
            </SELECT>
            <br>
            Vice-President :&nbsp <SELECT  class="" name="Vp" size="1"  style="width: 180px;">
              {% for l in all %}
              {% if l.role.role_str == 'Vice-President' %}
              <OPTION selected> {{l.user}}
                {% else%}
              <OPTION>{{l.user}}
                {% endif%}
                {% endfor %}
            </SELECT>
            <br>
            Tresorier : &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            <SELECT  class="" name="Tr" size="1"  style="width: 180px;">
              {% for l in all %}
              {% if l.role.role_str == 'Tresorier' %}
              <OPTION selected> {{l.user}}
                {% else%}
              <OPTION>{{l.user}}
                {% endif%}
                {% endfor %}
            </SELECT>
            <br>
            Secretaire : &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<SELECT  class="" name="Se" size="1"  style="width: 180px;">
              {% for l in all %}
              {% if l.role.role_str == 'Secretaire' %}
              <OPTION selected> {{l.user}}
                {% else%}
              <OPTION>{{l.user}}
                {% endif%}
                {% endfor %}
            </SELECT>
            <br>
            <input class="btn btn-sm btn-primary btn-block" type="submit" value="Changer le Bureau"   form="form1" style="background-color:  #41b2e6;" />

          </FORM>
        </div>

        {% else %}

        <div class="dropdown">
          <FORM method="get" id="form1" style="color:white">
            Vice-President :&nbsp <SELECT  class="" name="Vp" size="1"  style="width: 180px;">
              {% for l in members %}
              {% if l.role.role_str == 'Vice-President' %}
              <OPTION selected> {{l.user}}
                {% else%}
              <OPTION>{{l.user}}
                {% endif%}
                {% endfor %}
                {% for l in nobody %}
              <OPTION>{{l.user}}
                {% endfor %}
            </SELECT>
            <br>
            Tresorier : &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
            <SELECT  class="" name="Tr" size="1" style="width: 180px;">
              {% for l in members %}
              {% if l.role.role_str == 'Tresorier' %}
              <OPTION selected> {{l.user}}
                {% else%}
              <OPTION>{{l.user}}
                {% endif%}
                {% endfor %}
                {% for l in nobody %}
              <OPTION>{{l.user}}
                {% endfor %}
            </SELECT>
            <br>
            Secretaire :&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<SELECT  class="" name="Se" size="1"  style="width: 180px;">
              {% for l in members %}
              {% if l.role.role_str == 'Secretaire' %}
              <OPTION selected> {{l.user}}
                {% else%}
              <OPTION>{{l.user}}
                {% endif%}
                {% endfor %}
                {% for l in nobody %}
              <OPTION>{{l.user}}
                {% endfor %}
            </SELECT>

            <input class="btn btn-sm btn-primary btn-block" type="submit" value="Changer le Bureau"   form="form1" style="background-color:  #41b2e6;" />

          </FORM>
          <br>
        </div>
        {% endif%}
        {% endif%}


      </div>
      <div style="color: white" class="col-md-0">


      </div>
  </body>

yakachoisir/intraAsso/templates/intraAsso/assos_vice_president.html
<html>
  <head>
    <meta charset="utf-8">
    <time></time>
    <title></title>
    {% load static %}
    <link rel="stylesheet" type = "text/css" href="{% static 'intraAsso/bootstrap.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{% static 'intraAsso/yaka.css'%}" media="all"/>
    <style type= "text/css">
      .asteriskField{display: none;}
    </style>
  </head>
  <body class="text-center" style="background-image :url({% static 'intraAsso/image/backgroundEPITA.png'%})">
    <div class="topnav container-fluid" style="z-index: 1">
      <a href="https://www.epita.fr/">
        <img src="{% static 'intraAsso/image/Epita.png'%}" alt="" width="100px" height="64px" align="left" style=" margin-top:-25px">
      </a>
      <a class="active" align= "left"  href="{% url 'intraAsso:accueil' %}">Accueil</a>
      <a class="lien" href="{% url 'intraAsso:show_user' request.user.id %}">Mon Profil</a>
      <a class="lien"  align ="left"  href="{% url 'intraAsso:associations' %}">Association</a>
      <a class="lien"  align="left"  href="{% url 'intraAsso:create_asso' %}">Création d'association</a>
      <a class="lien"  align="left"  href="{% url 'intraAsso:actualite' %}">Actualités</a>
      <a class="lien" align= "right" style = "float : right"href="{% url 'intraAsso:logout' %}">Déconnexion</a>
      <h5 class= "bar" style="color: white;" align= "right">{{ request.user.first_name }} {{ request.user.last_name }}</h5>

      <form id="searchform" action="{% url 'intraAsso:research' %}" method="get" accept-charset="utf-8">
        <input class="searchfield" id="searchbox" name="q" type="text" placeholder="Recherche">
      </form>
    </div>
    <br><br>
    {% if association.club %}
    <h1 style="color: white"> Club "{{ association.name }}"<br><br>
      Association Tutrice "{{tuteur.name}}"
    </h1>

    {% else %}
    <h1 style="color: white">Association "{{ association.name }}"</h1>

    {% endif %}

<!--

        {% if abonne == 0 %}
        <a  href="{% url 'intraAsso:abonne' association.id %}"><button align=type="submit" class="btn btn-success btn-sm">S'abonner </button></a>
        {% else %}
        <a  href="{% url 'intraAsso:abonne' association.id %}"><button align=type="submit" class="btn btn-danger btn-sm">Se désabonner </button></a>
        {% endif %}

-->


    <br>
    <div class="row">

      <div class="col-md-4"></div>
      <div style="color: white"  class="col-md-4" >
        <div align="left">  <font style="font-weight:bold; text-align: justify-all;"> Description :</font>  {{association.description}}</div>
        <br>
        <div align="left">  <font style="font-weight:bold"> Site Web Officiel :</font>
          {% if association.site != "" %}
          <a class = "link" style= "color: white" href="{{association.site}}">{{association.site}}</a>
          {% else %}
          Aucun
          {% endif %}</div>
        <div align ="left">  <font style="font-weight:bold"> Adresse Mail Officiel :</font> {{association.mail}}</div>
        <br>
        {% if abonne == 0 %}
        <a  href="{% url 'intraAsso:abonne' association.id %}"><button align=type="submit" class="btn btn-success btn-sm">S'abonner </button></a>
        {% else %}
        <a  href="{% url 'intraAsso:abonne' association.id %}"><button align=type="submit" class="btn btn-danger btn-sm">Se désabonner </button></a>
        {% endif %}
        <br><br>
        <a  href="{% url 'intraAsso:edit_asso' association.id %}"> <button align=type="submit" class="btn btn-danger btn-sm">Editer les informations
        </button></a>
        {% if  enacs.enabled %}
        <a  href="{% url 'intraAsso:edit_enacs' association.id %}"><button align=type="submit" class="btn btn-danger btn-sm">Editer les points Enacs </button></a>
        {% endif%}
      <a  href="{% url 'intraAsso:create_actu' association.id %}"><button align=type="submit" class="btn btn-danger btn-sm">Créer une actualité</button></a>
        <br><br><br>
     </div>
      <div style="color: white" class="col-md-1"></div>
    </div>

    <div class="row">
      <div class="col-md-2"></div>
      <div style="color: white"  class="col-md-3" >
        <h4>Postulant :</h4><br>
        {% for l in postulants %}
        {{ l.user }}
        <a href="{% url 'intraAsso:validation_post' l.id %}"><button type="submit" class="btn btn-sm btn-success">Accepter</button></a>
        <a href="{% url 'intraAsso:refu_post' l.id %}"><button type="submit" class="btn btn-sm btn-danger">Refuser</button></a>
        <br>
        {% endfor %}
      </div>
      <div style="color: white"  class="col-md-3" >
        <div align ="left" style="text-align: left;">
          <h4> Membres :</h4><br>
          {% for l in nobody %}
          <a href="{% url 'intraAsso:show_user' president.user.id %}" style="color:white; text-decoration:none"> {{ l.user }}</a>
          <a href="{% url 'intraAsso:kick' l.id %}">
            <button type="submit" class="btn btn-sm btn-danger">Expulser</button>
          </a><br>
          {% endfor %}
        </div>
      </div>
      <div align ="left" style="text-align: left;color: white" class="col-md-3">
        <h4> Bureau :</h4><br>
        <div align="left"><a href="{% url 'intraAsso:show_user' president.user.id %}" style="color:white; text-decoration:none"> <font style="font-weight:bold">{{ president.role.role_str }}: </font>{{ president.user }} </a></div>
        {% for l in members %}
        <div align="left"><a href="{% url 'intraAsso:show_user' l.user.id %}"  style="color:white; text-decoration:none" > <font style="font-weight:bold">{{ l.role.role_str }}: </font>{{ l.user }} </a></div>
        {% endfor %}

        <br>
        <!--<a  href=""> <button align=type="submit" class="btn btn-danger btn-sm">Changer le bureau</button></a>-->
      </div>
      <div style="color: white" class="col-md-0"></div>

  </body>